name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2021.11=py37_0
  - alabaster=0.7.12=py37_0
  - anaconda=custom=py37_1
  - anaconda-client=1.9.0=py37hecd8cb5_0
  - anaconda-project=0.10.2=pyhd3eb1b0_0
  - anyio=2.2.0=py37hecd8cb5_1
  - appdirs=1.4.4=pyhd3eb1b0_0
  - applaunchservices=0.2.1=pyhd3eb1b0_0
  - appnope=0.1.2=py37hecd8cb5_1001
  - appscript=1.1.2=py37h9ed2024_0
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - argh=0.26.2=py37_0
  - argon2-cffi=20.1.0=py37h9ed2024_1
  - arrow=0.13.1=py37_0
  - asn1crypto=1.4.0=py_0
  - astroid=2.6.6=py37hecd8cb5_0
  - astropy=4.3.1=py37hf9932de_0
  - async_generator=1.10=py37h28b3542_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.shutil_get_terminal_size=1.0.0=pyhd3eb1b0_3
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bitarray=2.3.5=py37hca72f7f_0
  - bkcharts=0.2=py37_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h2842e9f_0
  - bokeh=2.4.2=py37hecd8cb5_0
  - boto=2.49.0=py37_0
  - bottleneck=1.3.2=py37hf1fa96c_1
  - brotli=1.0.9=hb1e8313_2
  - brotlipy=0.7.0=py37h9ed2024_1003
  - brunsli=0.1=h23ab428_0
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.18.1=hca72f7f_0
  - ca-certificates=2021.10.8=h033912b_0
  - cairo=1.14.12=hc4e6be7_4
  - catalogue=2.0.6=py37hf985489_2
  - certifi=2021.10.8=py37hf985489_2
  - cffi=1.15.0=py37hca72f7f_0
  - cfitsio=3.470=hee0f690_6
  - charls=2.2.0=h23ab428_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py37_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.11.0=py37hecd8cb5_0
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.7.3=py37h9ed2024_1
  - conda-token=0.3.0=pyhd3eb1b0_0
  - contextlib2=0.6.0.post1=pyhd3eb1b0_0
  - cookiecutter=1.7.2=pyhd3eb1b0_0
  - cryptography=36.0.0=py37hf6deb26_0
  - curl=7.80.0=hca72f7f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.6=py37hd8d24ac_2
  - cython=0.29.25=py37he9d5cce_0
  - cython-blis=0.7.7=py37h49e79e5_1
  - cytoolz=0.11.0=py37haf1e3a3_0
  - daal4py=2021.4.0=py37h24a4e90_0
  - dal=2021.4.0=hecd8cb5_689
  - dask=2021.10.0=pyhd3eb1b0_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=h18a8e69_0
  - debugpy=1.5.1=py37he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - distributed=2021.10.0=py37hecd8cb5_0
  - docutils=0.18.1=py37hecd8cb5_2
  - entrypoints=0.3=py37_0
  - et_xmlfile=1.1.0=py37hecd8cb5_0
  - expat=2.4.1=h23ab428_2
  - fastcache=1.1.0=py37h1de35cc_0
  - filelock=3.4.2=pyhd3eb1b0_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - fontconfig=2.13.1=ha9ee91d_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=hd8bbffd_0
  - fribidi=1.0.10=haf1e3a3_0
  - fsspec=2022.1.0=pyhd3eb1b0_0
  - get_terminal_size=1.0.0=h7520d66_0
  - gettext=0.21.0=h7535e17_0
  - gevent=21.8.0=py37h9ed2024_1
  - giflib=5.2.1=haf1e3a3_0
  - glib=2.63.1=hd977a24_0
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=h23ab428_2
  - gmpy2=2.0.8=py37h6ef4df4_2
  - graphite2=1.3.14=h38d11af_0
  - graphviz=2.40.1=hefbbd9a_2
  - greenlet=1.1.1=py37h23ab428_0
  - h5py=2.10.0=py37h3134771_0
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.4=hfa1e0ec_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - html5lib=1.1=pyhd3eb1b0_0
  - icu=58.2=h0a44026_3
  - imagecodecs=2021.8.26=py37ha952a84_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - imbalanced-learn=0.9.0=pyhd8ed1ab_0
  - importlib-metadata=4.8.2=py37hecd8cb5_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - inflection=0.5.1=py37hecd8cb5_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.4.1=py37hecd8cb5_1
  - ipython=7.31.1=py37hecd8cb5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jbig=2.1=h4d881f8_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.18.1=py37hecd8cb5_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_2
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h9ed2024_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py37hecd8cb5_0
  - jupyter_server=1.4.1=py37hecd8cb5_0
  - jupyterlab=3.2.1=pyhd3eb1b0_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.2=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=haf1e3a3_2
  - keyring=23.4.0=py37hecd8cb5_0
  - kiwisolver=1.3.1=py37h23ab428_0
  - krb5=1.19.2=hcd88c3b_0
  - langcodes=3.3.0=pyhd8ed1ab_0
  - lazy-object-proxy=1.6.0=py37h9ed2024_0
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libaec=1.0.4=hb1e8313_1
  - libarchive=3.4.2=haa3ed63_0
  - libcurl=7.80.0=h6dfd666_0
  - libcxx=12.0.0=h2f01273_0
  - libdeflate=1.8=h9ed2024_5
  - libedit=3.1.20210910=hca72f7f_0
  - libev=4.33=h9ed2024_1
  - libffi=3.2.1=h0a44026_1007
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - liblief=0.10.1=h0a44026_0
  - libllvm11=11.1.0=h9b2ccf5_0
  - libnghttp2=1.46.0=ha29bfda_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libspatialindex=1.9.3=h23ab428_0
  - libssh2=1.9.0=ha12b0ac_1
  - libtiff=4.2.0=h87d7836_0
  - libuv=1.40.0=haf1e3a3_0
  - libwebp=1.2.0=hacca55c_0
  - libwebp-base=1.2.0=h9ed2024_0
  - libxml2=2.9.12=hcdb78fc_0
  - libxslt=1.1.34=h83b36ba_0
  - libzopfli=1.0.3=hb1e8313_0
  - llvm-openmp=12.0.0=h0dcd299_1
  - llvmlite=0.37.0=py37he4411ff_1
  - locket=0.2.1=py37hecd8cb5_1
  - lxml=4.7.1=py37h65b224f_1
  - lz4-c=1.9.3=h23ab428_1
  - lzo=2.10=haf1e3a3_2
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.5.0=py37hecd8cb5_0
  - matplotlib-base=3.5.0=py37h4f681db_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py37h9ed2024_0
  - mkl_fft=1.3.1=py37h4ab4a9b_0
  - mkl_random=1.2.2=py37hb2f4e1b_0
  - mock=4.0.3=pyhd3eb1b0_0
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - mpi=1.0=mpich
  - mpich=3.3.2=hc856adb_0
  - mpmath=1.2.1=py37hecd8cb5_0
  - msgpack-python=1.0.2=py37hf7b0b51_1
  - multipledispatch=0.6.0=py37_0
  - munkres=1.1.4=py_0
  - murmurhash=1.0.7=py37he9d5cce_0
  - mypy_extensions=0.4.3=py37hecd8cb5_1
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.3.0=py37hecd8cb5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=hca72f7f_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - nltk=3.6.5=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.4.6=py37hecd8cb5_0
  - numba=0.54.1=py37hae1ba45_0
  - numexpr=2.8.1=py37h2e5f0a9_0
  - numpy=1.20.3=py37h4b4dc7a_0
  - numpy-base=1.20.3=py37he0bd621_0
  - numpy-financial=1.0.0=pyhd8ed1ab_0
  - numpydoc=1.2=pyhd3eb1b0_0
  - olefile=0.46=py37_0
  - openjpeg=2.4.0=h66ea3da_0
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - openssl=1.1.1n=h6c3fc93_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h743cdd8_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.42.4=h7e27002_1
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - path=16.2.0=pyhd3eb1b0_0
  - path.py=12.5.0=hd3eb1b0_0
  - pathlib2=2.3.6=py37hecd8cb5_2
  - pathspec=0.7.0=py_0
  - pathy=0.6.1=pyhd8ed1ab_0
  - patsy=0.5.2=py37hecd8cb5_0
  - pcre=8.45=h23ab428_0
  - pep8=1.7.1=py37_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py37h98e4679_0
  - pixman=0.40.0=h9ed2024_1
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - pluggy=1.0.0=py37hecd8cb5_0
  - ply=3.11=py37_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - preshed=3.0.6=py37hd8d24ac_1
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - psutil=5.8.0=py37h9ed2024_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.10.0=pyhd3eb1b0_0
  - py-lief=0.10.1=py37haf313ee_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py37h9ed2024_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pycrypto=2.6.1=py37haf1e3a3_10
  - pycurl=7.44.1=py37hbcfaee0_1
  - pydantic=1.8.2=py37h271585c_2
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pydotplus=2.0.2=pyh243d235_4
  - pyerfa=2.0.0=py37h9ed2024_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.9.6=py37hecd8cb5_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyodbc=4.0.32=py37he9d5cce_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.18.0=py37hca72f7f_0
  - pysocks=1.7.1=py37hecd8cb5_0
  - pytables=3.6.1=py37h5bccee9_0
  - pytest=6.2.5=py37hecd8cb5_2
  - python=3.7.7=hc70fcce_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-graphviz=0.16=pyhd3eb1b0_1
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python.app=3=py37hca72f7f_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.3=pyhd3eb1b0_0
  - pywavelets=1.1.1=py37haf1e3a3_2
  - pyyaml=6.0=py37hca72f7f_1
  - pyzmq=22.3.0=py37he9d5cce_2
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.2.2=pyhd3eb1b0_0
  - qtpy=1.11.2=pyhd3eb1b0_0
  - readline=8.1.2=hca72f7f_1
  - regex=2021.11.2=py37hca72f7f_0
  - requests=2.27.1=pyhd8ed1ab_0
  - ripgrep=12.1.1=0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py37hecd8cb5_1
  - ruamel_yaml=0.15.100=py37h9ed2024_0
  - scikit-image=0.18.3=py37hae1ba45_0
  - scikit-learn=1.0.2=py37hae1ba45_1
  - scikit-learn-intelex=2021.4.0=py37hecd8cb5_0
  - scipy=1.7.3=py37h8c7af03_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py37hecd8cb5_0
  - shellingham=1.4.0=pyh44b312d_0
  - simplegeneric=0.8.1=py37_2
  - singledispatch=3.7.0=pyhd3eb1b0_1001
  - sip=4.19.8=py37h0a44026_0
  - six=1.16.0=pyhd3eb1b0_0
  - smart_open=5.2.1=pyhd8ed1ab_0
  - snappy=1.1.8=hb1e8313_0
  - sniffio=1.2.0=py37hecd8cb5_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - spacy=3.2.1=py37hc29d2bd_0
  - spacy-legacy=3.0.9=pyhd8ed1ab_0
  - spacy-loggers=1.0.2=pyhd8ed1ab_0
  - sphinx=1.8.5=py37_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=5.1.5=py37hecd8cb5_1
  - spyder-kernels=2.1.3=py37hecd8cb5_0
  - sqlalchemy=1.4.27=py37hca72f7f_0
  - sqlite=3.37.2=h707629a_0
  - srsly=2.4.1=py37h23ab428_0
  - statsmodels=0.12.2=py37h9ed2024_0
  - sympy=1.9=py37hecd8cb5_0
  - tbb=2021.5.0=haf03e11_0
  - tbb4py=2021.5.0=py37haf03e11_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.9.4=py37hecd8cb5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - thinc=8.0.13=py37hc29d2bd_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.11=h7bc2e8c_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py37h9ed2024_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.4.3=py37h9ed2024_1
  - typer=0.4.1=pyhd8ed1ab_0
  - ujson=4.2.0=py37he9d5cce_0
  - unicodecsv=0.14.1=py37_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - unixodbc=2.3.9=haf1e3a3_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wasabi=0.9.1=pyhd8ed1ab_0
  - watchdog=2.1.6=py37h999c104_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - whichcraft=0.6.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py37_0
  - wordcloud=1.8.1=py37h271585c_2
  - wrapt=1.12.1=py37h1de35cc_1
  - wurlitzer=3.0.2=py37hecd8cb5_0
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.2=pyhd3eb1b0_0
  - xlwings=0.24.9=py37hecd8cb5_0
  - xlwt=1.3.0=py37_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h23ab428_0
  - zfp=0.5.5=he9d5cce_6
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h4dc903c_4
  - zope=1.0=py37_1
  - zope.event=4.5.0=py37_0
  - zope.interface=5.4.0=py37h9ed2024_0
  - zstd=1.4.9=h322a384_0
  - pip:
    - absl-py==1.0.0
    - altair==4.2.0
    - arch==5.2.0
    - astunparse==1.6.3
    - backports-zoneinfo==0.2.1
    - base58==2.1.1
    - bip32==2.1
    - bip44==0.1.1
    - blinker==1.4
    - cachetools==5.1.0
    - chardet==3.0.4
    - coincurve==15.0.1
    - commonmark==0.9.1
    - en-core-web-sm==3.2.0
    - eth-abi==2.1.1
    - eth-account==0.5.8
    - eth-hash==0.3.2
    - eth-keyfile==0.5.1
    - eth-keys==0.3.4
    - eth-rlp==0.2.1
    - eth-tester==0.5.0b3
    - eth-typing==2.3.0
    - eth-utils==1.10.0
    - flatbuffers==2.0
    - gast==0.5.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.46.1
    - hexbytes==0.2.2
    - ibm-cloud-sdk-core==3.15.1
    - ibm-watson==6.0.0
    - idna==2.8
    - ipfshttpclient==0.7.0a1
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.1
    - lru-dict==1.1.7
    - markdown==3.3.7
    - mnemonic==0.20
    - multiaddr==0.0.9
    - netaddr==0.8.0
    - newsapi-python==0.2.5
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - parsimonious==0.8.1
    - pip==22.1.2
    - property-cached==1.6.4
    - protobuf==3.20.1
    - psycopg2-binary==2.9.3
    - pyarrow==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodome==3.14.1
    - pydeck==0.7.1
    - pyjwt==2.3.0
    - pympler==1.0.1
    - pysha3==1.0.2
    - python-dotenv==0.20.0
    - pytz-deprecation-shim==0.1.0.post0
    - requests-oauthlib==1.3.1
    - rich==12.4.4
    - rlp==2.0.1
    - rsa==4.8
    - semantic-version==2.10.0
    - semver==2.13.0
    - smmap==5.0.0
    - streamlit==1.10.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.25.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - typing-extensions==3.10.0.2
    - tzdata==2022.1
    - tzlocal==4.2
    - validators==0.20.0
    - varint==1.0.2
    - web3==5.17.0
    - websocket-client==1.1.0
    - websockets==8.1
    - xgboost==1.6.1
